# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editorNotas.ui'
#
# Created: Sun Sep 27 21:34:59 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_editorNotas(object):
    def setupUi(self, editorNotas):
        editorNotas.setObjectName("editorNotas")
        editorNotas.setEnabled(True)
        editorNotas.resize(782, 678)
        self.verticalLayout_2 = QtGui.QVBoxLayout(editorNotas)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(editorNotas)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.listaProvedores = QtGui.QComboBox(editorNotas)
        self.listaProvedores.setCursor(QtCore.Qt.IBeamCursor)
        self.listaProvedores.setEditable(True)
        self.listaProvedores.setObjectName("listaProvedores")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.listaProvedores)
        self.label_5 = QtGui.QLabel(editorNotas)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.fichaTrabajo = QtGui.QComboBox(editorNotas)
        self.fichaTrabajo.setCursor(QtCore.Qt.ArrowCursor)
        self.fichaTrabajo.setEditable(True)
        self.fichaTrabajo.setObjectName("fichaTrabajo")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.fichaTrabajo)
        self.label_2 = QtGui.QLabel(editorNotas)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.dateEdit = QtGui.QDateEdit(editorNotas)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dateEdit)
        self.label_3 = QtGui.QLabel(editorNotas)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.formaPago = QtGui.QComboBox(editorNotas)
        self.formaPago.setEditable(True)
        self.formaPago.setObjectName("formaPago")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.formaPago)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_12 = QtGui.QLabel(editorNotas)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_11 = QtGui.QLabel(editorNotas)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.responsable = QtGui.QComboBox(editorNotas)
        self.responsable.setEditable(True)
        self.responsable.setObjectName("responsable")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.responsable)
        self.label_4 = QtGui.QLabel(editorNotas)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.tipoEntrega = QtGui.QComboBox(editorNotas)
        self.tipoEntrega.setObjectName("tipoEntrega")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.tipoEntrega)
        self.vendedor = QtGui.QComboBox(editorNotas)
        self.vendedor.setEditable(True)
        self.vendedor.setObjectName("vendedor")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.vendedor)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtGui.QTreeWidget(editorNotas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(651, 0))
        self.treeWidget.setAutoFillBackground(False)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setProperty("showDropIndicator", QtCore.QVariant(False))
        self.treeWidget.setDragEnabled(False)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setUniformRowHeights(True)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setObjectName("treeWidget")
        self.horizontalLayout.addWidget(self.treeWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.agregarItem = QtGui.QPushButton(editorNotas)
        self.agregarItem.setObjectName("agregarItem")
        self.verticalLayout.addWidget(self.agregarItem)
        self.editarItem = QtGui.QPushButton(editorNotas)
        self.editarItem.setObjectName("editarItem")
        self.verticalLayout.addWidget(self.editarItem)
        self.borrarItem = QtGui.QPushButton(editorNotas)
        self.borrarItem.setObjectName("borrarItem")
        self.verticalLayout.addWidget(self.borrarItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtGui.QLabel(editorNotas)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.subtotal = QtGui.QLineEdit(editorNotas)
        self.subtotal.setReadOnly(True)
        self.subtotal.setObjectName("subtotal")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.subtotal)
        self.label_6 = QtGui.QLabel(editorNotas)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.iva21 = QtGui.QLineEdit(editorNotas)
        self.iva21.setReadOnly(True)
        self.iva21.setObjectName("iva21")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.iva21)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtGui.QLabel(editorNotas)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.descuento = QtGui.QLineEdit(editorNotas)
        self.descuento.setReadOnly(True)
        self.descuento.setObjectName("descuento")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.descuento)
        self.label_7 = QtGui.QLabel(editorNotas)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.iva105 = QtGui.QLineEdit(editorNotas)
        self.iva105.setReadOnly(True)
        self.iva105.setObjectName("iva105")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.iva105)
        self.label_9 = QtGui.QLabel(editorNotas)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_4 = QtGui.QLineEdit(editorNotas)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtGui.QDialogButtonBox(editorNotas)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.actionAgregar_Item = QtGui.QAction(editorNotas)
        self.actionAgregar_Item.setObjectName("actionAgregar_Item")
        self.label.setBuddy(self.listaProvedores)
        self.label_5.setBuddy(self.fichaTrabajo)
        self.label_2.setBuddy(self.dateEdit)
        self.label_3.setBuddy(self.formaPago)
        self.label_8.setBuddy(self.subtotal)

        self.retranslateUi(editorNotas)
        QtCore.QMetaObject.connectSlotsByName(editorNotas)
        editorNotas.setTabOrder(self.listaProvedores, self.vendedor)
        editorNotas.setTabOrder(self.vendedor, self.fichaTrabajo)
        editorNotas.setTabOrder(self.fichaTrabajo, self.responsable)
        editorNotas.setTabOrder(self.responsable, self.dateEdit)
        editorNotas.setTabOrder(self.dateEdit, self.formaPago)
        editorNotas.setTabOrder(self.formaPago, self.agregarItem)
        editorNotas.setTabOrder(self.agregarItem, self.editarItem)
        editorNotas.setTabOrder(self.editarItem, self.borrarItem)
        editorNotas.setTabOrder(self.borrarItem, self.subtotal)
        editorNotas.setTabOrder(self.subtotal, self.descuento)
        editorNotas.setTabOrder(self.descuento, self.iva21)
        editorNotas.setTabOrder(self.iva21, self.iva105)
        editorNotas.setTabOrder(self.iva105, self.lineEdit_4)
        editorNotas.setTabOrder(self.lineEdit_4, self.buttonBox)
        editorNotas.setTabOrder(self.buttonBox, self.treeWidget)

    def retranslateUi(self, editorNotas):
        editorNotas.setWindowTitle(QtGui.QApplication.translate("editorNotas", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("editorNotas", "&Proveedor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("editorNotas", "Ficha de &Trabajo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("editorNotas", "Fecha de E&ntrega:", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit.setDisplayFormat(QtGui.QApplication.translate("editorNotas", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("editorNotas", "&Forma de Pago:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("editorNotas", "Vendedor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("editorNotas", "Responsable:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("editorNotas", "Entrega:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("editorNotas", "Cantidad", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("editorNotas", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("editorNotas", "Precio Unitario", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(3, QtGui.QApplication.translate("editorNotas", "Precio Total", None, QtGui.QApplication.UnicodeUTF8))
        self.agregarItem.setText(QtGui.QApplication.translate("editorNotas", "&Agregar Item", None, QtGui.QApplication.UnicodeUTF8))
        self.editarItem.setText(QtGui.QApplication.translate("editorNotas", "&Editar Item", None, QtGui.QApplication.UnicodeUTF8))
        self.borrarItem.setText(QtGui.QApplication.translate("editorNotas", "&Borrar Item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("editorNotas", "Subtotal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("editorNotas", "Iva 21%:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("editorNotas", "Descuento:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("editorNotas", "Iva 10,5%:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("editorNotas", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAgregar_Item.setText(QtGui.QApplication.translate("editorNotas", "Agregar Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAgregar_Item.setToolTip(QtGui.QApplication.translate("editorNotas", "Agrega un Item a la nota de pedido", None, QtGui.QApplication.UnicodeUTF8))

